### ISSUE TITLE
Allow Gameplay Button Input for all classes by Player agnostic of key and button presses

### ISSUE THREAD

**Issue by Aetolia** [Aetolia/Aetolia#19]
- Allow other gameobjects access user input via gameplay keys
- Hide the input methods behind players
- Hide the buttons and keys behind gameplay keys
- Allow keys to be matched up to gameplay buttons so users will be able to assign them
- Allow player input devices to both be automatically and manually assigned.

**Comment by ScottGarryFoster** [comment]
https://github.com/Aetolia/Aetolia/issues/21

Gameplay profiles is a requirement for this task

**Comment by ScottGarryFoster** [comment]
Moved to Vinyl. https://github.com/Aetolia/Vinyl/issues/1
